[package]
authors = ["Sebastian Messmer <messmer@cryfs.org>"]
edition = "2018"
name = "cryfs-blockstore"
version = "0.1.0"

[dependencies]
anyhow = "^1.0.37"
cxx = {version = "^1.0.27", features = ["c++14"]}
sysinfo = "^0.15.5"
rand = "^0.8.1"

[build-dependencies]
cxx-build = "^1.0.27"

[lib]
crate-type = ["staticlib"]

[profile.release]
lto = "fat"
